language: rust
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: beta
    - os: linux
      rust: stable

    - os: osx
      rust: nightly
    - os: osx
      rust: beta
    - os: osx
      rust: stable

script:
  - (cd dbgp && cargo build --verbose)
  - (cd dbgp && cargo test --verbose)
  - (cd dbgp && cargo doc --verbose)
  - (cd dbgp_capi && cargo build --verbose)
  - (cd dbgp_capi && cargo test --verbose)
  - (cd dbgp_capi && cargo doc --verbose)

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install cargo-travis &&
        (cd dbgp && cargo coveralls);
    fi
