language: rust
sudo: false

os:
  - linux
  - osx
rust:
  - nightly
  #- beta
  #- stable

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  fast_finish: true

script:
  - (cd dbgp && cargo build --verbose)
  - (cd dbgp && cargo test --verbose)
  - (cd dbgp && cargo doc --verbose)
  - (cd dbgp_capi && cargo build --verbose)
  - (cd dbgp_capi && cargo test --verbose)
  - (cd dbgp_capi && cargo doc --verbose)

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install cargo-travis &&
        (cd dbgp && cargo coveralls) &&
        (cd dbgp_capi && cargo coveralls);
    fi
