[package]
name = "dbgp"
version = "0.0.1"
authors = ["Afonso Bordado <afonsobordado@az8.co>"]
license-file = "../LICENSE"
readme = "../README"

[dependencies]
url = "1.4.0"
xml-rs = "0.4.1"
base64 = "0.4.1"

[lib]
name = "dbgp"
crate-type = ["rlib", "dylib"]
