/*
 * Copyright (c) the dbgp contributors. All rights reserved.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. This file is also subject
 * to the Linking exception provided in the LICENSE file that
 * accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 */

extern crate cheddar;

static LICENSE_HEADER: &'static str = "\
// THIS FILE IS AUTOGENERATED BY libdbgp_capi/build.rs - DO NOT EDIT
//
// Copyright (c) the libdbgp contributors. All rights reserved.
//
// This code is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License version 2 only, as
// published by the Free Software Foundation. This file is also subject
// to the Linking exception provided in the LICENSE file that
// accompanied this code.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// version 2 for more details (a copy is included in the LICENSE file that
// accompanied this code).
//
// You should have received a copy of the GNU General Public License version
// 2 along with this work; if not, write to the Free Software Foundation,
// Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
";

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");

    // Generate libdbgp.h with GPL header
    let mut c = cheddar::Cheddar::new().expect("could not read manifest");
    let license = LICENSE_HEADER.to_owned();

    for line in license.lines() {
        c.insert_code(line);
        c.insert_code("\n");
    }

    c.run_build("include/libdbgp.h");
}
